# version: "3.8"

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/24
          ip_range: 172.29.0.0/24
          gateway: 172.29.0.1

services:
  django-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      app_net:
        ipv4_address: 172.29.0.4
    environment:
      - PYTHONUNBUFFERED=1
    command: "poetry run python cat_app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./cat_app/db.sqlite3:/app/cat_app/db.sqlite3
      - ./cat_app/logs:/app/cat_app/logs
      - ./cat_app/api/migrations:/app/cat_app/api/migrations
    depends_on:
      - redis
      - nginx

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      app_net:
        ipv4_address: 172.29.0.2
    volumes:
      - ./cat_app/static:/var/www/html/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      app_net:
        ipv4_address: 172.29.0.3
    volumes:
      - redis_data:/data

volumes:
  redis_data:
